set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN V17 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN V15 [get_ports clear]
set_property IOSTANDARD LVCMOS33 [get_ports clear]

set_property PACKAGE_PIN V4 [get_ports {seg_sel[3]}]
set_property PACKAGE_PIN U4 [get_ports {seg_sel[2]}]
set_property PACKAGE_PIN U2 [get_ports {seg_sel[1]}]
set_property PACKAGE_PIN W4 [get_ports {seg_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[0]}]


set_property PACKAGE_PIN V7 [get_ports {seg_data[7]}]
set_property PACKAGE_PIN W7 [get_ports {seg_data[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg_data[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg_data[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg_data[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg_data[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg_data[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[0]}]
set_property PACKAGE_PIN V16 [get_ports open_stop]
set_property IOSTANDARD LVCMOS33 [get_ports open_stop]
set_property PACKAGE_PIN W16 [get_ports choose1or001]
set_property IOSTANDARD LVCMOS33 [get_ports choose1or001]
set_property PACKAGE_PIN W17 [get_ports up_down]
set_property IOSTANDARD LVCMOS33 [get_ports up_down]
set_property PACKAGE_PIN W15 [get_ports switch]
set_property IOSTANDARD LVCMOS33 [get_ports switch]
set_property PACKAGE_PIN U18 [get_ports get_time]
set_property IOSTANDARD LVCMOS33 [get_ports get_time]



set_property PACKAGE_PIN P19 [get_ports {vga_hs}]
set_property PACKAGE_PIN R19 [get_ports {vga_vs}]

set_property PACKAGE_PIN G19 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN H19 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN J19 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN N19 [get_ports {vga_r[3]}]

set_property PACKAGE_PIN N18 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN L18 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN K18 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}]

set_property PACKAGE_PIN J17 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN H17 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN D17 [get_ports {vga_g[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_hs}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_vs}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]

